# Generated by Django 3.0.4 on 2020-03-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('song', models.FileField(upload_to='songd')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
